
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate


# Include dirs
zone: !include_dir_merge_list includes/zone
sensor: !include_dir_merge_list includes/sensors
group: !include_dir_merge_named includes/groups
light: !include_dir_merge_list includes/lights
switch: !include_dir_merge_list includes/switches
scene: !include_dir_merge_list includes/scenes
script: !include_dir_merge_list includes/scripts
automation: !include_dir_merge_list includes/automations
input_boolean: !include_dir_merge_named includes/input_boolean
input_datetime: !include_dir_merge_named includes/input_datetime
input_number: !include_dir_merge_named includes/input_number
input_select: !include_dir_merge_named includes/input_select

